import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRef, useState } from "react";
export default function Home() {
  const [feedback, setFeedback] = useState([]);
  const emailRef = useRef();
  const feedbackRef = useRef();

  const handleSubmit = (e) => {
    e.preventDefault();
    const email = emailRef.current.value;
    const text = feedbackRef.current.value;

    fetch("/api/feedback", {
      method: "POST",
      body: JSON.stringify({ email, text }),
      headers: {
        "Content-Type": "application/json",
      },
    })
      .then((res) => res.json())
      .then((d) => setFeedback(d.feedback));
  };

  const loadData = () => {
    fetch("/api/feedback")
      .then((res) => res.json())
      .then(console.log);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Home Page</h1>
        <form onSubmit={handleSubmit}>
          <div>
            <label htmlFor="email">Email</label>
            <input type={"email"} id="email" ref={emailRef} />
          </div>
          <div>
            <label htmlFor="feedback" ref={feedbackRef}>
              feedback
            </label>
            <textarea id="feedback" rows="5"></textarea>
          </div>
          <button type="submit">submit</button>
        </form>
        <hr />
        <button onClick={loadData}>Load Data</button>
        <ul>
          {feedback.map((i) => (
            <li id={i.id}>{i.text}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}
